import React from "react";
import VerticalCard from "./VerticalCard";

import './LastNews.scss'

function LastNews() {
    const news = [
        { title: "UNESCO adds new sites to the World Heritage List", image: "/images/1.png", text: "UNESCO’s World Heritage Committee has wrapped up its deliberations related to sites that are in danger and began adding new sites on Saturday to its prestigious World Heritage List./nSites in Ukraine — the St. Sophia Cathedral and the Kyiv-Pechersk Lavra monastery complex, both located in the capital city of Kyiv, and the historical center of Lviv in western Ukraine — were deemed to be “in danger” earlier this week./nDeliberations started Saturday considering 50 sites nominated for the well-known World Heritage List./nThe Forest Massif of Odzala-Kokoua in Congo and the volcanoes and forests of Mount Pelée and the Pitons on the French island of Martinique, were chosen to be inscribed to the World Heritage List on the first day." },
        { title: "Getaways where cars and phones are banned", image: "/images/2.png", text: "On-board liquids are typically limited by airport security, but unfortunately, they were free-flowing on two recent flights across North America. (Assume the brace position: Some gruesome tales ahead.)/nAir Canada has apologized after two passengers on a flight from Las Vegas to Montreal last month were told to sit in poorly cleaned seats that were still covered in vomit from a previous flight./nAnd a Delta Air Lines flight from Atlanta to Barcelona on September 1 was forced to do a U-turn after a passenger “had diarrhea all the way through the airplane,” creating a biohazard issue./nIt concludes a summer of effluence that began in June when a traveler on an Air France flight was handed wet wipes by cabin crew after he found his footwell still wet with blood and feces from a previous passenger." },
        { title: "Italy’s vacation hotspot wants to ban new Airbnbs", image: "/images/3.png", text: "As Europe continues to be squeezed by overtourism and short-term rentals mushroom to accommodate visitors, cities across the continent are noting more and more that residents are being squeezed out./nNow, one of Europe’s biggest tourist destinations is taking action. The city of Florence has announced plans to ban new short-term rentals such as Airbnbs./nThe new legislation, which will be voted on next Wednesday and is expected to be active by November, will ban any further properties in the historic center of the city being registered as short-term rentals./n Mayor of Florence Dario Nardella said in a statement shared with CNN that the “very important” legislation was tackling “an emergency situation of total deregulation.”/n “We are witnessing a progressive growth in the influx of tourists which has become even more pronounced since the pandemic,” he added./n Figures from the city council show that 75% of Florence’s short-term rentals are concentrated in just 5% of the municipal territory – the city’s centro storico, the birthplace of the Renaissance and a UNESCO World Heritage site. The legislation aims to tackle that 5%." },
        { title: "What to do if you have Labor Day travel plans in Idalia’s path", image: "/images/4.png", text: "No, says AAA Travel’s Paula Twidale, with the caveat that the situation requires monitoring.“We encourage consumers to keep travel plans,” but to monitor the storm’s effects, and look for airline waivers for re-booking, “if necessary,” said Twidale, senior vice president of AAA Travel./nRescheduling makes sense for hard-hit areas, according to Clint Henderson, managing editor at travel site The Points Guy.Visit St. Pete/Clearwater, which represents two popular beach spots, said in an emailed statement Wednesday afternoon that the destination “fared well and saw minimal damage.” Access was temporarily restricted to Pinellas County’s barrier islands, but it has since been restored./nThe tourism organization recommends that visitors contact their accommodations to find out when properties will be open and accepting guests.Visit Tampa Bay said Thursday morning that the area is “100% open.”Tampa International Airport reopened to arrivals Wednesday afternoon and fully reopened early Thursday." },
        { title: "The parents hiking America’s longest trails with five kids", image: "/images/5.png", text: "Currently around halfway through the Pacific Crest Trail, a 2,653-mile (4,270-kilometer) trail extending from the border of Mexico through California, Oregon, and Washington to Canada, the Netteburgs feel very lucky to be able to hike these iconic trails as a family.“We realize, a lot of people can’t do it,” Danae tells CNN Travel. “They [either] don’t have the time or money or they don’t want to. So we’re very blessed.”/nDanae and Olen, who are both physicians, met at medical school in 2003 and married around three years later. In 2010, the couple relocated to Chad, a landlocked country in north-central Africa, to run a medical practice and went on to have their children, who were all born in the US.While the pair had gone on a few backpacking trips together over the years, including a visit to the Canadian Rockies after they got married, it wasn’t until Juniper, their fourth child, was aged around two that they decided to attempt an extensive trail as a family." },
        { title: "Bhutan cuts daily tourist fee by half to lure more visitors", image: "/images/6.png", text: "The Himalayan kingdom of Bhutan is to halve the $200 daily fee it charges tourists in an effort to boost a sector still struggling to recover a year after the end of Covid-19 restrictions.Bhutan raised its “Sustainable Development Fee” to $200 per visitor per night, from $65, when it ended two years of Covid restrictions in September last year saying the money would go to offset the carbon generated by visitors./nThe new rate of $100 per night would come into effect from September and last for four years, the government said in a statement late on Friday.“This is in view of the important role of the tourism sector in generating employment, earning foreign exchange … and in boosting overall economic growth,” it said." },
        { title: "Nearly 50 global treasures could be about to get UNESCO’s World Heritage status", image: "/images/7.png", text: "A collection of tombs from Korea’s ancient Gaya confederacy, a Viking age ring fortress in Denmark, an ancient Thai town and a 2,000-year-old earthworks in Ohio are among the contenders for inscription on the UNESCO World Heritage List this year./nFollowing much deliberation, the United Nations Educational, Scientific and Cultural Organization (UNESCO) is shortly expected to announce which sites have been given the honor of a place on its list of World Heritage Sites./n This year, the UNESCO World Heritage Committee is reviewing nominations from both 2022 and 2023, with participants from across the world attending the session in Riyadh, Saudi Arabia to examine almost 50 contenders." },
        { title: "Russian landmark added to UNESCO World Heritage List", image: "/images/8.png", text: "A university observatory in Russia has been inscribed onto the UNESCO World Heritage List.The astronomical observatories of Kazan Federal University, located in the city of Kazan, were added to the esteemed list on Monday as UNESCO’s World Heritage Committee continued its deliberations in Riyadh, Saudi Arabia./n The site is made up of the Kazan Observatory, built in 1837 in the historical center of the city, and a complex that includes the suburban Engelhardt Astronomical Observatory and various historical buildings." },
        { title: "America’s driest, hottest national park is still closed – but not for the reason you might think", image: "/images/9.png", text: "Death Valley is the driest national park in the United States, receiving an average of about 2.2 inches of rain a year. It’s also regarded as the hottest place on Earth. So it might come as a bit of a shock to learn the park been closed for more than two weeks – but not from all this excessive heat we’ve suffered through this summer. It’s the rainy remnants of Hurricane Hilary (remember that storm?) that are the culprit./n On August 20, some 2.2 inches (55.88 mm) of rain was measured at Furnace Creek in Death Valley, making it the all-time wettest day recorded for that location, the National Park Service said in a recent news release.The storm dumped so much rain on a park that gets so little that it left the fragile landscape in rough shape. “Extensive damage including undercutting and pavement loss has been found on major roads in the park and many roads are covered with debris,” the release said." },
        { title: "Austria offers free rail travel for a year - if you get a tattoo", image: "/images/3.png", text: "In travel news this week: tattoos and graffiti cause trouble in Europe, a baby giraffe is born without spots at a Tennessee zoo – plus we want to hear from you if you’re currently chasing your lost luggage with a tracking device./n You’ve probably heard the adage that “there are no bad ideas.” But that was before Austria’s climate minister endorsed a campaign to give people a year’s free public transport if they got the rail card logo tattooed on their body./nBacklash was swift, reports Salzburger Nachrichten, after music festival attendees were invited to turn their flesh into a permanent billboard for the Klimaticket (“Climate Ticket”), which usually costs just over 1,000 euros for unlimited rail, bus, tram and metro travel throughout the country. That translates to about $1,080 dollars – or, you know, two to five treatments for laser tattoo removal./nThe Italian city of Florence was also struck by foolhardy inking this week. Two German tourists were arrested for spraying Munich soccer-related graffiti on the 460-year-old Vasari Corridor leading up to the Uffizi Galleries. The museum director is calling for “an iron fist of the law.”" },
    ]

    return (
        <div className="last-news-container">
            {news.map(item => <VerticalCard data={item} />)}
        </div>
    )
}

export default LastNews;